services:
  - type: web
    name: gofight-backend
    env: node
    region: frankfurt    # (ou oregon selon ta région)
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
